/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as noauthLRouteImport } from './routes/(noauth)/_l'
import { Route as noauthLIndexRouteImport } from './routes/(noauth)/_l.index'
import { Route as authDashboardLRouteImport } from './routes/(auth)/dashboard/_l'
import { Route as authDashboardLIndexRouteImport } from './routes/(auth)/dashboard/_l.index'
import { Route as authDashboardLLinksIndexRouteImport } from './routes/(auth)/dashboard/_l.links.index'

const noauthLRoute = noauthLRouteImport.update({
  id: '/(noauth)/_l',
  getParentRoute: () => rootRouteImport,
} as any)
const noauthLIndexRoute = noauthLIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => noauthLRoute,
} as any)
const authDashboardLRoute = authDashboardLRouteImport.update({
  id: '/(auth)/dashboard/_l',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authDashboardLIndexRoute = authDashboardLIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authDashboardLRoute,
} as any)
const authDashboardLLinksIndexRoute =
  authDashboardLLinksIndexRouteImport.update({
    id: '/links/',
    path: '/links/',
    getParentRoute: () => authDashboardLRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof authDashboardLRouteWithChildren
  '/': typeof noauthLIndexRoute
  '/dashboard/': typeof authDashboardLIndexRoute
  '/dashboard/links/': typeof authDashboardLLinksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof noauthLIndexRoute
  '/dashboard': typeof authDashboardLIndexRoute
  '/dashboard/links': typeof authDashboardLLinksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(noauth)/_l': typeof noauthLRouteWithChildren
  '/(auth)/dashboard/_l': typeof authDashboardLRouteWithChildren
  '/(noauth)/_l/': typeof noauthLIndexRoute
  '/(auth)/dashboard/_l/': typeof authDashboardLIndexRoute
  '/(auth)/dashboard/_l/links/': typeof authDashboardLLinksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dashboard' | '/' | '/dashboard/' | '/dashboard/links/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/dashboard/links'
  id:
    | '__root__'
    | '/(noauth)/_l'
    | '/(auth)/dashboard/_l'
    | '/(noauth)/_l/'
    | '/(auth)/dashboard/_l/'
    | '/(auth)/dashboard/_l/links/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  noauthLRoute: typeof noauthLRouteWithChildren
  authDashboardLRoute: typeof authDashboardLRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(noauth)/_l': {
      id: '/(noauth)/_l'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof noauthLRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(noauth)/_l/': {
      id: '/(noauth)/_l/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof noauthLIndexRouteImport
      parentRoute: typeof noauthLRoute
    }
    '/(auth)/dashboard/_l': {
      id: '/(auth)/dashboard/_l'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authDashboardLRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/dashboard/_l/': {
      id: '/(auth)/dashboard/_l/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authDashboardLIndexRouteImport
      parentRoute: typeof authDashboardLRoute
    }
    '/(auth)/dashboard/_l/links/': {
      id: '/(auth)/dashboard/_l/links/'
      path: '/links'
      fullPath: '/dashboard/links/'
      preLoaderRoute: typeof authDashboardLLinksIndexRouteImport
      parentRoute: typeof authDashboardLRoute
    }
  }
}

interface noauthLRouteChildren {
  noauthLIndexRoute: typeof noauthLIndexRoute
}

const noauthLRouteChildren: noauthLRouteChildren = {
  noauthLIndexRoute: noauthLIndexRoute,
}

const noauthLRouteWithChildren =
  noauthLRoute._addFileChildren(noauthLRouteChildren)

interface authDashboardLRouteChildren {
  authDashboardLIndexRoute: typeof authDashboardLIndexRoute
  authDashboardLLinksIndexRoute: typeof authDashboardLLinksIndexRoute
}

const authDashboardLRouteChildren: authDashboardLRouteChildren = {
  authDashboardLIndexRoute: authDashboardLIndexRoute,
  authDashboardLLinksIndexRoute: authDashboardLLinksIndexRoute,
}

const authDashboardLRouteWithChildren = authDashboardLRoute._addFileChildren(
  authDashboardLRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  noauthLRoute: noauthLRouteWithChildren,
  authDashboardLRoute: authDashboardLRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
