/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as noauthLRouteImport } from './routes/(noauth)/_l'
import { Route as noauthNotfoundIndexRouteImport } from './routes/(noauth)/notfound.index'
import { Route as noauthLoginIndexRouteImport } from './routes/(noauth)/login.index'
import { Route as noauthLIndexRouteImport } from './routes/(noauth)/_l.index'
import { Route as authDashboardLRouteImport } from './routes/(auth)/dashboard/_l'
import { Route as noauthLoginSuccessIndexRouteImport } from './routes/(noauth)/login/success.index'
import { Route as authDashboardLIndexRouteImport } from './routes/(auth)/dashboard/_l.index'
import { Route as authDashboardLLinksIndexRouteImport } from './routes/(auth)/dashboard/_l.links.index'
import { Route as authDashboardLLinksAnalyticsIndexLinkIdRouteImport } from './routes/(auth)/dashboard/_l.links.analytics.index.$linkId'

const noauthLRoute = noauthLRouteImport.update({
  id: '/(noauth)/_l',
  getParentRoute: () => rootRouteImport,
} as any)
const noauthNotfoundIndexRoute = noauthNotfoundIndexRouteImport.update({
  id: '/(noauth)/notfound/',
  path: '/notfound/',
  getParentRoute: () => rootRouteImport,
} as any)
const noauthLoginIndexRoute = noauthLoginIndexRouteImport.update({
  id: '/(noauth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const noauthLIndexRoute = noauthLIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => noauthLRoute,
} as any)
const authDashboardLRoute = authDashboardLRouteImport.update({
  id: '/(auth)/dashboard/_l',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const noauthLoginSuccessIndexRoute = noauthLoginSuccessIndexRouteImport.update({
  id: '/(noauth)/login/success/',
  path: '/login/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const authDashboardLIndexRoute = authDashboardLIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authDashboardLRoute,
} as any)
const authDashboardLLinksIndexRoute =
  authDashboardLLinksIndexRouteImport.update({
    id: '/links/',
    path: '/links/',
    getParentRoute: () => authDashboardLRoute,
  } as any)
const authDashboardLLinksAnalyticsIndexLinkIdRoute =
  authDashboardLLinksAnalyticsIndexLinkIdRouteImport.update({
    id: '/links/analytics/index/$linkId',
    path: '/links/analytics/index/$linkId',
    getParentRoute: () => authDashboardLRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof authDashboardLRouteWithChildren
  '/': typeof noauthLIndexRoute
  '/login/': typeof noauthLoginIndexRoute
  '/notfound/': typeof noauthNotfoundIndexRoute
  '/dashboard/': typeof authDashboardLIndexRoute
  '/login/success/': typeof noauthLoginSuccessIndexRoute
  '/dashboard/links/': typeof authDashboardLLinksIndexRoute
  '/dashboard/links/analytics/index/$linkId': typeof authDashboardLLinksAnalyticsIndexLinkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof noauthLIndexRoute
  '/login': typeof noauthLoginIndexRoute
  '/notfound': typeof noauthNotfoundIndexRoute
  '/dashboard': typeof authDashboardLIndexRoute
  '/login/success': typeof noauthLoginSuccessIndexRoute
  '/dashboard/links': typeof authDashboardLLinksIndexRoute
  '/dashboard/links/analytics/index/$linkId': typeof authDashboardLLinksAnalyticsIndexLinkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(noauth)/_l': typeof noauthLRouteWithChildren
  '/(auth)/dashboard/_l': typeof authDashboardLRouteWithChildren
  '/(noauth)/_l/': typeof noauthLIndexRoute
  '/(noauth)/login/': typeof noauthLoginIndexRoute
  '/(noauth)/notfound/': typeof noauthNotfoundIndexRoute
  '/(auth)/dashboard/_l/': typeof authDashboardLIndexRoute
  '/(noauth)/login/success/': typeof noauthLoginSuccessIndexRoute
  '/(auth)/dashboard/_l/links/': typeof authDashboardLLinksIndexRoute
  '/(auth)/dashboard/_l/links/analytics/index/$linkId': typeof authDashboardLLinksAnalyticsIndexLinkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/login/'
    | '/notfound/'
    | '/dashboard/'
    | '/login/success/'
    | '/dashboard/links/'
    | '/dashboard/links/analytics/index/$linkId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notfound'
    | '/dashboard'
    | '/login/success'
    | '/dashboard/links'
    | '/dashboard/links/analytics/index/$linkId'
  id:
    | '__root__'
    | '/(noauth)/_l'
    | '/(auth)/dashboard/_l'
    | '/(noauth)/_l/'
    | '/(noauth)/login/'
    | '/(noauth)/notfound/'
    | '/(auth)/dashboard/_l/'
    | '/(noauth)/login/success/'
    | '/(auth)/dashboard/_l/links/'
    | '/(auth)/dashboard/_l/links/analytics/index/$linkId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  noauthLRoute: typeof noauthLRouteWithChildren
  authDashboardLRoute: typeof authDashboardLRouteWithChildren
  noauthLoginIndexRoute: typeof noauthLoginIndexRoute
  noauthNotfoundIndexRoute: typeof noauthNotfoundIndexRoute
  noauthLoginSuccessIndexRoute: typeof noauthLoginSuccessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(noauth)/_l': {
      id: '/(noauth)/_l'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof noauthLRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(noauth)/notfound/': {
      id: '/(noauth)/notfound/'
      path: '/notfound'
      fullPath: '/notfound/'
      preLoaderRoute: typeof noauthNotfoundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(noauth)/login/': {
      id: '/(noauth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof noauthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(noauth)/_l/': {
      id: '/(noauth)/_l/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof noauthLIndexRouteImport
      parentRoute: typeof noauthLRoute
    }
    '/(auth)/dashboard/_l': {
      id: '/(auth)/dashboard/_l'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authDashboardLRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(noauth)/login/success/': {
      id: '/(noauth)/login/success/'
      path: '/login/success'
      fullPath: '/login/success/'
      preLoaderRoute: typeof noauthLoginSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/dashboard/_l/': {
      id: '/(auth)/dashboard/_l/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authDashboardLIndexRouteImport
      parentRoute: typeof authDashboardLRoute
    }
    '/(auth)/dashboard/_l/links/': {
      id: '/(auth)/dashboard/_l/links/'
      path: '/links'
      fullPath: '/dashboard/links/'
      preLoaderRoute: typeof authDashboardLLinksIndexRouteImport
      parentRoute: typeof authDashboardLRoute
    }
    '/(auth)/dashboard/_l/links/analytics/index/$linkId': {
      id: '/(auth)/dashboard/_l/links/analytics/index/$linkId'
      path: '/links/analytics/index/$linkId'
      fullPath: '/dashboard/links/analytics/index/$linkId'
      preLoaderRoute: typeof authDashboardLLinksAnalyticsIndexLinkIdRouteImport
      parentRoute: typeof authDashboardLRoute
    }
  }
}

interface noauthLRouteChildren {
  noauthLIndexRoute: typeof noauthLIndexRoute
}

const noauthLRouteChildren: noauthLRouteChildren = {
  noauthLIndexRoute: noauthLIndexRoute,
}

const noauthLRouteWithChildren =
  noauthLRoute._addFileChildren(noauthLRouteChildren)

interface authDashboardLRouteChildren {
  authDashboardLIndexRoute: typeof authDashboardLIndexRoute
  authDashboardLLinksIndexRoute: typeof authDashboardLLinksIndexRoute
  authDashboardLLinksAnalyticsIndexLinkIdRoute: typeof authDashboardLLinksAnalyticsIndexLinkIdRoute
}

const authDashboardLRouteChildren: authDashboardLRouteChildren = {
  authDashboardLIndexRoute: authDashboardLIndexRoute,
  authDashboardLLinksIndexRoute: authDashboardLLinksIndexRoute,
  authDashboardLLinksAnalyticsIndexLinkIdRoute:
    authDashboardLLinksAnalyticsIndexLinkIdRoute,
}

const authDashboardLRouteWithChildren = authDashboardLRoute._addFileChildren(
  authDashboardLRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  noauthLRoute: noauthLRouteWithChildren,
  authDashboardLRoute: authDashboardLRouteWithChildren,
  noauthLoginIndexRoute: noauthLoginIndexRoute,
  noauthNotfoundIndexRoute: noauthNotfoundIndexRoute,
  noauthLoginSuccessIndexRoute: noauthLoginSuccessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
